env:
  browser: false
  commonjs: true
  es2021: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {}
globals:
  fetch: false # eslint ignore 'fetch' global imported by 'isomorphic-fetch'
