openapi: 3.0.3
info:
  title: PerfectFit
  version: "0.0.1"
  description: PerfectFit Sensor API
  contact:
    name: Netherlands eScience Center
    url: https://www.esciencecenter.nl/
    email: info@esciencecenter.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: API version 1
    url: /sensor/
# tags:
#   - name: Sensor Data
#     description: Sensor Data Controller
paths:
  # TODO: rename the endpoint if it's needed to organize data in other way
  # e.g. to "activity", "session", etc.
  /accelerometer:
    post:
      tags:
        - Accelerometer
      summary: Create Accelerometer Data
      operationId: api.sensor.Accelerometer.post
      requestBody:
        $ref: '#/components/requestBodies/Accelerometer'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Validation exception
  /step:
    post:
      tags:
        - step
      summary: Update The Step Count
      operationId: api.sensor.Step.post
      requestBody:
        $ref: '#/components/requestBodies/Step'
      responses:
        '200':
          description: Step Count Updated
        '405':
          description: Validation exception
        
components:
  schemas:
    Accelerometer:
      type: object
      properties:
        userID:
          type: string
          format: email
        sensorData:
          type: number
    Step:
      type: object
      properties:
        user:
          type: string
          description: hash_id of the user
          example: 9o0xZ0JGRauKnlY31dYJjA
        token:
          type: string
          description: token of the user
          example: "bf12441748548f45cd1ca9e6edc9a538f088289afd0b4ce2f008459f064b7c1b"
        localTime:
          type: string
          example: "2023-01-19T09:00:00.000"
        utcTime:
          type: number
          example: 1674115200000
        timezone:
          type: string
          example: "Europe/Amsterdam"
        value:
          type: number
          example: 14

  requestBodies:
    Accelerometer:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Accelerometer'
    Step:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Step'