openapi: 3.0.3
info:
  title: PerfectFit
  version: "0.0.1"
  description: PerfectFit Sensor API
  contact:
    name: Netherlands eScience Center
    url: https://www.esciencecenter.nl/
    email: info@esciencecenter.nl
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - description: API version 1
    url: /sensor/
# tags:
#   - name: Sensor Data
#     description: Sensor Data Controller
paths:
  # TODO: rename the endpoint if it's needed to organize data in other way
  # e.g. to "activity", "session", etc.
  /accelerometer:
    post:
      tags:
        - Accelerometer
      summary: Create Accelerometer Data
      operationId: sensor_api.sensorapi.api.sensor.Accelerometer.post
      requestBody:
        $ref: '#/components/requestBodies/Accelerometer'
      responses:
        '200':
          description: Successful operation
        '405':
          description: Validation exception
components:
  schemas:
    Accelerometer:
      type: object
      properties:
        userID:
          type: string
          format: email
        sensorData:
          type: number
  requestBodies:
    Accelerometer:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Accelerometer'