name: Node.js CI

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd niceday-api
      - run: npm ci
      - run: npm run build --if-present
      - name: Test niceday-api
        run: npm test

      - run: cd../niceday-broker
      - run: npm ci
      - run: npm run build --if-present
      - name: Test niceday-broker
        run: npm test