name: Python + Node.js CI

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  build-model:
    name: Build, test, and upload model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # Smallest value for all max_history parameters in config.yml. 
    - name: Validate stories
       run: |
        rasa data validate --max-history 10
    - name: Train model
      run: |
        rasa train
   