on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Cloud Check
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
        persist-credentials: false  # To make Github uses personal access token

    # Gather coverage for Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip and install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-dev.txt
    - name: Run unit tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD
        pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
    - name: Correct coverage paths
      run: sed -i "s+$PWD/++g" coverage.xml

    # Gather coverage for node.js
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: git config --global url."https://${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}@github.com/".insteadOf ssh://git@github.com/

    - run: npm ci --prefix niceday-api
    - name: Test niceday-api with coverage
      run: npm test --prefix niceday-api

    - run: npm ci --prefix niceday-broker
    - name: Test niceday-broker with coverage
      run: npm test --prefix niceday-broker

    # Perform sonarcloud scan
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}