on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]
name: Sonar Cloud Check
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip and install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install -r requirements-dev.txt
    - name: Run unit tests with coverage
      run: |
        export PYTHONPATH=$PYTHONPATH:$PWD
        pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
    - name: Correct coverage paths
      run: sed -i "s+$PWD/++g" coverage.xml
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}